##**Imporing Pandas Library**

In [3]:
import pandas as pd

##**Loading Datasets in pandas**

In [4]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
print(df.columns)

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

##**Groupby & Aggregate**

In [ ]:
df.groupby('longitude').mean()

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
longitude,,,,,,,,
-124.18,40.790000,40.000000,1398.000000,311.00,788.000000,279.000000,1.466800,64600.0
-124.17,41.800000,16.000000,2739.000000,480.00,1259.000000,436.000000,3.755700,109400.0
-124.16,41.070000,38.000000,2254.500000,459.75,1002.000000,427.250000,2.177775,81475.0
-124.15,40.780000,41.000000,2127.000000,358.00,911.000000,349.000000,3.171100,104200.0
-124.14,40.706667,25.666667,1700.666667,339.00,922.666667,342.666667,3.123200,100400.0
...,...,...,...,...,...,...,...,...
-114.98,33.070000,18.000000,1183.000000,363.00,374.000000,127.000000,3.160700,57500.0
-114.62,33.620000,26.000000,18.000000,3.00,5.000000,3.000000,0.536000,275000.0
-114.61,33.620000,16.000000,1187.000000,261.00,1115.000000,242.000000,2.175900,61500.0
-114.55,32.800000,19.000000,2570.000000,820.00,1431.000000,608.000000,1.275000,56100.0
-114.49,33.970000,17.000000,2809.000000,635.00,83.000000,45.000000,1.615400,87500.0

In [ ]:
df.groupby('median_house_value').count().head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
median_house_value,,,,,,,,
22500.0,1,1,1,1,1,1,1,1
37500.0,1,1,1,1,1,1,1,1
39200.0,1,1,1,1,1,1,1,1
39800.0,1,1,1,1,1,1,1,1
40000.0,1,1,1,1,1,1,1,1
41500.0,1,1,1,1,1,1,1,1
42500.0,1,1,1,1,1,1,1,1
42700.0,1,1,1,1,1,1,1,1
43100.0,1,1,1,1,1,1,1,1
43300.0,1,1,1,1,1,1,1,1

In [ ]:
minimum_median_house_value = df.groupby('median_house_value').min()
minimum_median_house_value

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
median_house_value,,,,,,,,
22500.0,-117.16,32.71,52.0,845.0,451.0,1230.0,375.0,1.0918
37500.0,-123.08,40.40,10.0,365.0,102.0,140.0,49.0,1.7969
39200.0,-119.97,36.44,18.0,1128.0,237.0,772.0,220.0,2.1771
39800.0,-117.65,35.00,36.0,1184.0,316.0,672.0,241.0,1.9107
40000.0,-122.06,37.39,22.0,1236.0,290.0,413.0,274.0,3.6875
...,...,...,...,...,...,...,...,...
494700.0,-118.43,34.04,52.0,2425.0,435.0,962.0,412.0,5.8587
495500.0,-118.39,33.88,33.0,2543.0,439.0,1098.0,416.0,5.9683
495800.0,-122.71,37.88,21.0,2845.0,552.0,599.0,250.0,4.3125
500000.0,-122.43,34.05,23.0,1880.0,361.0,798.0,357.0,4.4000
500001.0,-122.49,32.68,5.0,42.0,14.0,26.0,14.0,0.4999

In [ ]:
maximum_median_house_value = df.groupby('median_house_value').max()
maximum_median_house_value

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
median_house_value,,,,,,,,
22500.0,-117.16,32.71,52.0,845.0,451.0,1230.0,375.0,1.0918
37500.0,-123.08,40.40,10.0,365.0,102.0,140.0,49.0,1.7969
39200.0,-119.97,36.44,18.0,1128.0,237.0,772.0,220.0,2.1771
39800.0,-117.65,35.00,36.0,1184.0,316.0,672.0,241.0,1.9107
40000.0,-122.06,37.39,22.0,1236.0,290.0,413.0,274.0,3.6875
...,...,...,...,...,...,...,...,...
494700.0,-118.43,34.04,52.0,2425.0,435.0,962.0,412.0,5.8587
495500.0,-118.39,33.88,33.0,2543.0,439.0,1098.0,416.0,5.9683
495800.0,-122.71,37.88,21.0,2845.0,552.0,599.0,250.0,4.3125
500000.0,-118.44,37.80,52.0,4911.0,693.0,1480.0,606.0,6.7770
500001.0,-116.99,37.87,52.0,18132.0,5419.0,7431.0,4930.0,15.0001

In [ ]:
sum_median_house_value = df.groupby('median_house_value').sum()
sum_median_house_value

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
median_house_value,,,,,,,,
22500.0,-117.16,32.71,52.0,845.0,451.0,1230.0,375.0,1.0918
37500.0,-123.08,40.40,10.0,365.0,102.0,140.0,49.0,1.7969
39200.0,-119.97,36.44,18.0,1128.0,237.0,772.0,220.0,2.1771
39800.0,-117.65,35.00,36.0,1184.0,316.0,672.0,241.0,1.9107
40000.0,-122.06,37.39,22.0,1236.0,290.0,413.0,274.0,3.6875
...,...,...,...,...,...,...,...,...
494700.0,-118.43,34.04,52.0,2425.0,435.0,962.0,412.0,5.8587
495500.0,-118.39,33.88,33.0,2543.0,439.0,1098.0,416.0,5.9683
495800.0,-122.71,37.88,21.0,2845.0,552.0,599.0,250.0,4.3125
500000.0,-485.18,146.01,159.0,11675.0,2061.0,4120.0,1932.0,20.9244
500001.0,-14956.77,4394.00,4117.0,401543.0,70778.0,150869.0,65051.0,962.9998

In [ ]:
df.groupby('median_house_value').describe()

                   longitude                                                 \
                       count       mean       std     min      25%      50%
median_house_value
22500.0                  1.0 -117.16000       NaN -117.16 -117.160 -117.160
37500.0                  1.0 -123.08000       NaN -123.08 -123.080 -123.080
39200.0                  1.0 -119.97000       NaN -119.97 -119.970 -119.970
39800.0                  1.0 -117.65000       NaN -117.65 -117.650 -117.650
40000.0                  1.0 -122.06000       NaN -122.06 -122.060 -122.060
...                      ...        ...       ...     ...      ...      ...
494700.0                 1.0 -118.43000       NaN -118.43 -118.430 -118.430
495500.0                 1.0 -118.39000       NaN -118.39 -118.390 -118.390
495800.0                 1.0 -122.71000       NaN -122.71 -122.710 -122.710
500000.0                 4.0 -121.29500  1.915803 -122.43 -122.385 -122.155
500001.0               125.0 -119.65416  1.921542 -122.49 -122.060 -118.460

                                    latitude           ... households          \
                        75%     max    count     mean  ...        75%     max
median_house_value                                     ...
22500.0            -117.160 -117.16      1.0  32.7100  ...      375.0   375.0
37500.0            -123.080 -123.08      1.0  40.4000  ...       49.0    49.0
39200.0            -119.970 -119.97      1.0  36.4400  ...      220.0   220.0
39800.0            -117.650 -117.65      1.0  35.0000  ...      241.0   241.0
40000.0            -122.060 -122.06      1.0  37.3900  ...      274.0   274.0
...                     ...     ...      ...      ...  ...        ...     ...
494700.0           -118.430 -118.43      1.0  34.0400  ...      412.0   412.0
495500.0           -118.390 -118.39      1.0  33.8800  ...      416.0   416.0
495800.0           -122.710 -122.71      1.0  37.8800  ...      250.0   250.0
500000.0           -121.065 -118.44      4.0  36.5025  ...      565.5   606.0
500001.0           -118.330 -116.99    125.0  35.1520  ...      596.0  4930.0

                   median_income                                        \
                           count      mean       std     min       25%
median_house_value
22500.0                      1.0  1.091800       NaN  1.0918  1.091800
37500.0                      1.0  1.796900       NaN  1.7969  1.796900
39200.0                      1.0  2.177100       NaN  2.1771  2.177100
39800.0                      1.0  1.910700       NaN  1.9107  1.910700
40000.0                      1.0  3.687500       NaN  3.6875  3.687500
...                          ...       ...       ...     ...       ...
494700.0                     1.0  5.858700       NaN  5.8587  5.858700
495500.0                     1.0  5.968300       NaN  5.9683  5.968300
495800.0                     1.0  4.312500       NaN  4.3125  4.312500
500000.0                     4.0  5.231100  1.062860  4.4000  4.633175
500001.0                   125.0  7.703998  3.409691  0.4999  4.975700


                       50%        75%      max
median_house_value
22500.0             1.0918   1.091800   1.0918
37500.0             1.7969   1.796900   1.7969
39200.0             2.1771   2.177100   2.1771
39800.0             1.9107   1.910700   1.9107
40000.0             3.6875   3.687500   3.6875
...                    ...        ...      ...
494700.0            5.8587   5.858700   5.8587
495500.0            5.9683   5.968300   5.9683
495800.0            4.3125   4.312500   4.3125
500000.0            4.8737   5.471625   6.7770
500001.0            7.4001  10.223300  15.0001

[1784 rows x 64 columns]

##**Aggregating in Pandas**

In [ ]:
df.groupby('households').agg(['count', 'min', 'max' , 'sum' , 'mean']).head(10)

           longitude                                     latitude         \
               count     min     max     sum        mean    count    min
households
2.0                1 -116.95 -116.95 -116.95 -116.950000        1  33.86
3.0                2 -117.12 -114.62 -231.74 -115.870000        2  32.66
7.0                2 -121.89 -118.44 -240.33 -120.165000        2  34.04
8.0                2 -122.49 -121.29 -243.78 -121.890000        2  37.33
9.0                5 -121.96 -117.11 -599.09 -119.818000        5  32.66
10.0               1 -121.84 -121.84 -121.84 -121.840000        1  36.62
11.0               1 -118.36 -118.36 -118.36 -118.360000        1  33.82
12.0               1 -117.09 -117.09 -117.09 -117.090000        1  34.01
13.0               1 -117.30 -117.30 -117.30 -117.300000        1  34.10
14.0               3 -121.90 -117.12 -357.01 -119.003333        3  33.81

                                   ... median_income                   \
              max     sum    mean  ...         count     min      max
households                         ...
2.0         33.86   33.86  33.860  ...             1  1.6250   1.6250
3.0         33.62   66.28  33.140  ...             2  0.5360   1.1250
7.0         37.42   71.46  35.730  ...             2  2.1875   7.7197
8.0         38.00   75.33  37.665  ...             2  4.0000   7.7197
9.0         37.74  179.73  35.946  ...             5  0.5360  15.0001
10.0        36.62   36.62  36.620  ...             1  2.2250   2.2250
11.0        33.82   33.82  33.820  ...             1  6.1359   6.1359
12.0        34.01   34.01  34.010  ...             1  4.0556   4.0556
13.0        34.10   34.10  34.100  ...             1  2.5625   2.5625
14.0        37.39  105.30  35.100  ...             3  1.7361   4.1667

                              median_house_value                      \
                sum      mean              count       min       max
households
2.0          1.6250  1.625000                  1   55000.0   55000.0
3.0          1.6610  0.830500                  2   60000.0  275000.0
7.0          9.9072  4.953600                  2  225000.0  225000.0
8.0         11.7197  5.859850                  2   75000.0  400000.0
9.0         21.3040  4.260800                  5  118800.0  450000.0
10.0         2.2250  2.225000                  1  150000.0  150000.0
11.0         6.1359  6.135900                  1  330000.0  330000.0
12.0         4.0556  4.055600                  1  131300.0  131300.0
13.0         2.5625  2.562500                  1   75000.0   75000.0
14.0         9.1736  3.057867                  3  162500.0  500001.0


                  sum           mean
households
2.0           55000.0   55000.000000
3.0          335000.0  167500.000000
7.0          450000.0  225000.000000
8.0          475000.0  237500.000000
9.0         1256300.0  251260.000000
10.0         150000.0  150000.000000
11.0         330000.0  330000.000000
12.0         131300.0  131300.000000
13.0          75000.0   75000.000000
14.0         825001.0  275000.333333

[10 rows x 40 columns]

In [7]:
df.groupby('households').agg({'households' : ['count', 'min', 'max' , 'sum' , 'mean']}).head(3)

           households
                count  min  max   sum mean
households
2.0                 1  2.0  2.0   2.0  2.0
3.0                 2  3.0  3.0   6.0  3.0
7.0                 2  7.0  7.0  14.0  7.0

In [8]:
df.groupby('households').describe()

           longitude                                                          \
               count     mean       std     min       25%      50%       75%
households
2.0              1.0 -116.950       NaN -116.95 -116.9500 -116.950 -116.9500
3.0              2.0 -115.870  1.767767 -117.12 -116.4950 -115.870 -115.2450
7.0              2.0 -120.165  2.439518 -121.89 -121.0275 -120.165 -119.3025
8.0              2.0 -121.890  0.848528 -122.49 -122.1900 -121.890 -121.5900
9.0              5.0 -119.818  2.104738 -121.96 -121.0400 -120.920 -118.0600
...              ...      ...       ...     ...       ...      ...       ...
3293.0           1.0 -121.730       NaN -121.73 -121.7300 -121.730 -121.7300
3958.0           1.0 -117.270       NaN -117.27 -117.2700 -117.270 -117.2700
4176.0           1.0 -117.220       NaN -117.22 -117.2200 -117.220 -117.2200
4855.0           1.0 -121.530       NaN -121.53 -121.5300 -121.530 -121.5300
4930.0           1.0 -118.440       NaN -118.44 -118.4400 -118.440 -118.4400

                   latitude          ... median_income           \
               max    count    mean  ...           75%      max
households                           ...
2.0        -116.95      1.0  33.860  ...      1.625000   1.6250
3.0        -114.62      2.0  33.140  ...      0.977750   1.1250
7.0        -118.44      2.0  35.730  ...      6.336650   7.7197
8.0        -121.29      2.0  37.665  ...      6.789775   7.7197
9.0        -117.11      5.0  35.946  ...      2.375000  15.0001
...            ...      ...     ...  ...           ...      ...
3293.0     -121.73      1.0  37.680  ...      5.449600   5.4496
3958.0     -117.27      1.0  33.150  ...      4.635700   4.6357
4176.0     -117.22      1.0  32.860  ...      3.628700   3.6287
4855.0     -121.53      1.0  38.480  ...      4.881100   4.8811
4930.0     -118.44      1.0  33.980  ...      5.335900   5.3359

           median_house_value                                               \
                        count      mean            std       min       25%
households
2.0                       1.0   55000.0            NaN   55000.0   55000.0
3.0                       2.0  167500.0  152027.957955   60000.0  113750.0
7.0                       2.0  225000.0       0.000000  225000.0  225000.0
8.0                       2.0  237500.0  229809.703886   75000.0  156250.0
9.0                       5.0  251260.0  141850.935845  118800.0  162500.0
...                       ...       ...            ...       ...       ...
3293.0                    1.0  238900.0            NaN  238900.0  238900.0
3958.0                    1.0  244900.0            NaN  244900.0  244900.0
4176.0                    1.0  280800.0            NaN  280800.0  280800.0
4855.0                    1.0  212200.0            NaN  212200.0  212200.0
4930.0                    1.0  500001.0            NaN  500001.0  500001.0


                 50%       75%       max
households
2.0          55000.0   55000.0   55000.0
3.0         167500.0  221250.0  275000.0
7.0         225000.0  225000.0  225000.0
8.0         237500.0  318750.0  400000.0
9.0         175000.0  350000.0  450000.0
...              ...       ...       ...
3293.0      238900.0  238900.0  238900.0
3958.0      244900.0  244900.0  244900.0
4176.0      280800.0  280800.0  280800.0
4855.0      212200.0  212200.0  212200.0
4930.0      500001.0  500001.0  500001.0

[1026 rows x 64 columns]